# Generated by Django 4.2.17 on 2024-12-11 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0002_rename_artist_id_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songgenre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='songgenre',
            name='song_id',
        ),
        migrations.AddField(
            model_name='songgenre',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songId', to='tunaapi.genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songgenre',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genreId', to='tunaapi.song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='tunaapi.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
